replicaCount: 2
image:
  repository: "shivjalkote/eks-nginx-app"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
